baseURL = 'https://emy.sh/'
languageCode = 'en-us'
title = 'Emily'
theme = "hugo-theme-console"

[params]
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
    name = "posts/"
    url = "posts/"
  [[params.navlinks]]
    name = "github/"
    url = "https://github.com/EmilyCSh"
