baseURL = 'https://emy.sh/'
languageCode = 'en-us'
title = 'Emily'
theme = "hugo-theme-console"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
    name = "articles/"
    url = "articles/"
  [[params.navlinks]]
    name = "posts/"
    url = "posts/"
  [[params.navlinks]]
    name = "tools/"
    url = "tools/"
